site_name: CoffeeTable

pages:
  - Home: index.md
  - Papers: references.md

theme_dir: mkdocs

site_description: CoffeeTable café e muita leitura!
site_url: https://pyoceans.github.io/CoffeeTable
repo_url: https://pyoceans.com/ocefpaf/CoffeeTable
site_author: Filipe Fernandes & Juliana Leonel
site_favicon: favicon.png
docs_dir: src
site_dir: _site
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a><br /> <span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Dataset" property="dct:title" rel="dct:type"> "CoffeeTable"</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://ocefpaf.github.io/" property="cc:attributionName" rel="cc:attributionURL">Filipe Fernandes</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US"> Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.<br />
markdown_extensions:
    - toc:
        permalink: ""
    - extra
    - smarty
    - math
    - markdown_checklist.extension
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']
google_analytics: ['UA-9133259-16', 'ocefpaf.github.io']
